#!/usr/bin/env bash
set -euo pipefail

# validate.sh — Session validation pipeline
#
# Runs all quality gates. Exit non-zero = session incomplete.
# Generated by livery/bin/scaffold. Extend per project.

echo "=== Validation Pipeline ==="

# --- Gate 1: Formatting ---
echo ""
echo "--- Gate 1: cargo fmt ---"
cargo fmt --check

# --- Gate 2: Linting ---
echo ""
echo "--- Gate 2: cargo clippy ---"
cargo clippy --workspace -- -D warnings

# --- Gate 3: Tests ---
echo ""
echo "--- Gate 3: cargo test ---"
cargo test --workspace

# --- Gate 4: Doc coverage ---
echo ""
echo "--- Gate 4: Doc comments on pub items ---"
RUSTDOCFLAGS="-D missing_docs" cargo doc --no-deps --quiet 2>/dev/null || {
    echo "WARNING: Missing doc comments on pub items."
    echo "Run: RUSTDOCFLAGS=\"-D missing_docs\" cargo doc --no-deps"
    # Non-blocking during early development; becomes blocking at 500+ LOC
    LOC=$(find crates -name '*.rs' -not -path '*/tests/*' -exec cat {} + 2>/dev/null | wc -l | tr -d ' ')
    if [ "$LOC" -gt 500 ]; then
        echo "FAIL: Project has $LOC lines — doc coverage is mandatory."
        exit 1
    else
        echo "(non-blocking: project has only $LOC lines)"
    fi
}

# --- Gate 5: Livery lint rules ---
echo ""
echo "--- Gate 5: Livery lint rules ---"
if [[ -x "livery/bin/lint-rules" ]]; then
    livery/bin/lint-rules
else
    echo "WARNING: livery/bin/lint-rules not found or not executable."
fi

# --- Gate 6: Prism quality gate (graduated thresholds) ---
echo ""
echo "--- Gate 6: Prism quality gate ---"
if [[ -x "livery/bin/prism" ]]; then
    LOC=$(find crates -name '*.rs' -not -path '*/tests/*' -exec cat {} + 2>/dev/null | wc -l | tr -d ' ')

    if [ "$LOC" -lt 200 ]; then
        echo "  (early project: $LOC LOC — Prism runs in lenient mode)"
        cat > /tmp/prism-graduated.toml << 'TOML'
[quality]
min_doc_coverage = 0
max_cyclomatic = 25
max_cognitive = 40
max_fn_lines_warn = 150
max_fn_lines_fail = 300
[testing]
min_test_ratio = 0.5
require_integration_tests = false
[safety]
max_unsafe_blocks = 0
TOML
        livery/bin/prism check . --config /tmp/prism-graduated.toml --no-deps --no-coverage
    elif [ "$LOC" -lt 2000 ]; then
        echo "  (growing project: $LOC LOC — raised thresholds)"
        cat > /tmp/prism-graduated.toml << 'TOML'
[quality]
min_doc_coverage = 60
max_cyclomatic = 20
max_cognitive = 30
max_fn_lines_warn = 100
max_fn_lines_fail = 200
[testing]
min_test_ratio = 1.0
require_integration_tests = false
[safety]
max_unsafe_blocks = 0
TOML
        livery/bin/prism check . --config /tmp/prism-graduated.toml --no-deps --no-coverage
    else
        echo "  (production: $LOC LOC — full thresholds)"
        livery/bin/prism check . --strict --no-deps --no-coverage
    fi
else
    echo "WARNING: livery/bin/prism not executable. Run prism check manually."
fi

# --- Gate 7: TDD audit ---
echo ""
echo "--- Gate 7: TDD audit ---"
if [[ -x "livery/bin/tdd-audit" ]]; then
    livery/bin/tdd-audit || {
        EXIT_CODE=$?
        if [[ "$EXIT_CODE" -eq 2 ]]; then
            echo "FAIL: TDD audit failed. Most commits lack test evidence."
            exit 1
        fi
        # Exit code 1 = warning, non-blocking
        echo "(TDD audit passed with warnings)"
    }
else
    echo "WARNING: livery/bin/tdd-audit not found or not executable."
fi

# --- Gate 8: Refactor evidence ---
echo ""
echo "--- Gate 8: Refactor evidence ---"
if [[ -x "livery/bin/refactor-check" ]]; then
    livery/bin/refactor-check || {
        EXIT_CODE=$?
        if [[ "$EXIT_CODE" -eq 2 ]]; then
            echo "FAIL: REFACTOR-EVIDENCE.md not found."
            echo "Document the three refactoring passes before closing the session."
            exit 1
        fi
        # Exit code 1 = warning (incomplete but present)
        echo "(Refactor evidence present but incomplete — review manually)"
    }
else
    echo "WARNING: livery/bin/refactor-check not found or not executable."
fi

# --- Gate 9: Commit message format ---
echo ""
echo "--- Gate 9: Commit message format ---"
if [[ -x "livery/bin/commit-check" ]]; then
    livery/bin/commit-check || {
        EXIT_CODE=$?
        if [[ "$EXIT_CODE" -eq 2 ]]; then
            echo "FAIL: Majority of commits violate message format."
            exit 1
        fi
        echo "(Commit format check passed with warnings)"
    }
else
    echo "WARNING: livery/bin/commit-check not found or not executable."
fi

echo ""
echo "=== All gates passed ==="
